apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-players-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: apex-sync-players
              image: apex-sync-players:1.4.0
              imagePullPolicy: IfNotPresent
              env:
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: apex-api-sync-secret
                      key: API_KEY
                - name: MONGO_CONNECTION_STRING
                  valueFrom:
                    secretKeyRef:
                      name: apex-api-sync-secret
                      key: MONGO_CONNECTION_STRING
                - name: MONGO_PLAYERS_DATABASE
                  value: playersDB
                - name: MONGO_PLAYERS_COLLECTION
                  value: players
                - name: MONGO_GAMES_DATABASE
                  value: gamesDB
                - name: MONGO_GAMES_COLLECTION
                  value: games
          restartPolicy: OnFailure
